In [2]:
import pandas as pd

# Creamos el diccionario simulando datos extraídos de una base de datos
datos_usuarios = {
    "id_usuario": [101, 102, 103, 104, 105],
    "edad": [28, 34, 29, 42, 22],
    "suscripcion_activa": [True, False, True, True, False],
    "tipo_plan": ["Premium", "Gratis", "Premium", "Basico", "Gratis"]
}

# Lo convertimos a DataFrame
df = pd.DataFrame(datos_usuarios)

# Mostramos la tabla
df

   id_usuario  edad  suscripcion_activa tipo_plan
0         101    28                True   Premium
1         102    34               False    Gratis
2         103    29                True   Premium
3         104    42                True    Basico
4         105    22               False    Gratis

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_usuario          5 non-null      int64
 1   edad                5 non-null      int64
 2   suscripcion_activa  5 non-null      bool
 3   tipo_plan           5 non-null      object
dtypes: bool(1), int64(2), object(1)
memory usage: 257.0+ bytes

In [1]:
import pandas as pd
import numpy as np

datos_api = {
    "Ticker": ["AAPL", "MSFT", "TSLA", "AMZN"],
    "Sector": ["Tecnología", "Tecnología", "Automotriz", "Retail"],
    "Precio": [175.50, 310.20, None, 135.00],
    "Volumen_Operaciones": [10200, 8500, 15000, np.nan]
}


df_mercado = pd.DataFrame(datos_api)

df_mercado

  Ticker      Sector  Precio  Volumen_Operaciones
0   AAPL  Tecnología   175.5              10200.0
1   MSFT  Tecnología   310.2               8500.0
2   TSLA  Automotriz     NaN              15000.0
3   AMZN      Retail   135.0                  NaN

In [2]:
df_mercado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Ticker               4 non-null      object
 1   Sector               4 non-null      object
 2   Precio               3 non-null      float64
 3   Volumen_Operaciones  3 non-null      float64
dtypes: float64(2), object(2)
memory usage: 260.0+ bytes

In [3]:
precio_promedio = df_mercado["Precio"].mean()

df_mercado["Precio"] = df_mercado["Precio"].fillna(precio_promedio)

df_mercado["Volumen_Operaciones"] = df_mercado["Volumen_Operaciones"].fillna(0)

df_mercado

  Ticker      Sector  Precio  Volumen_Operaciones
0   AAPL  Tecnología   175.5              10200.0
1   MSFT  Tecnología   310.2               8500.0
2   TSLA  Automotriz   206.9              15000.0
3   AMZN      Retail   135.0                  0.0

In [4]:
df_mercado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Ticker               4 non-null      object
 1   Sector               4 non-null      object
 2   Precio               4 non-null      float64
 3   Volumen_Operaciones  4 non-null      float64
dtypes: float64(2), object(2)
memory usage: 260.0+ bytes

In [16]:
df_tech = df_mercado.loc[df_mercado["Sector"] == "Tecnología"]

df_tech

  Ticker      Sector  Precio  Volumen_Operaciones
0   AAPL  Tecnología   175.5              10200.0
1   MSFT  Tecnología   310.2               8500.0

In [17]:
df_prueba = df_mercado.iloc[2:4]

df_prueba

  Ticker      Sector  Precio  Volumen_Operaciones
2   TSLA  Automotriz   206.9              15000.0
3   AMZN      Retail   135.0                  0.0

In [19]:
# Pruébalo después en tu VS Code, verás cómo Sector vuelve a ser una columna normal
volumen_por_sector = df_mercado.groupby("Sector")["Volumen_Operaciones"].sum().reset_index()
volumen_por_sector

       Sector  Volumen_Operaciones
0  Automotriz              15000.0
1      Retail                  0.0
2  Tecnología              18700.0

In [20]:
datos_corporativos = {
    "Ticker": ["AAPL", "MSFT", "TSLA", "AMZN", "GOOGL"],
    "Nombre_Completo": ["Apple Inc.", "Microsoft Corp.", "Tesla Inc.", "Amazon.com Inc.", "Alphabet Inc."],
    "Año_Fundacion": [1976, 1975, 2003, 1994, 1998]
}
df_info = pd.DataFrame(datos_corporativos)

In [21]:
df_final = pd.merge(df_mercado, df_info, on="Ticker", how="inner")


df_final

,Ticker,Sector,Precio,Volumen_Operaciones,Nombre_Completo,Año_Fundacion
0,AAPL,Tecnología,175.5,10200.0,Apple Inc.,1976
1,MSFT,Tecnología,310.2,8500.0,Microsoft Corp.,1975
2,TSLA,Automotriz,206.9,15000.0,Tesla Inc.,2003
3,AMZN,Retail,135.0,0.0,Amazon.com Inc.,1994