In [1]:
import pandas as pd

# Datos JSON complejos y anidados (típicos de APIs o NoSQL)
datos_anidados = [
    {"id_orden": 101, "cliente": {"nombre": "Eduardo", "nivel": "VIP"}, "monto": 1500.50},
    {"id_orden": 102, "cliente": {"nombre": "Andrea", "nivel": "Regular"}, "monto": 800.00},
    {"id_orden": 103, "cliente": {"nombre": "Carlos", "nivel": "VIP"}, "monto": 2300.10}
]

   id_orden                                   cliente   monto
0       101     {'nombre': 'Eduardo', 'nivel': 'VIP'}  1500.5
1       102  {'nombre': 'Andrea', 'nivel': 'Regular'}   800.0
2       103      {'nombre': 'Carlos', 'nivel': 'VIP'}  2300.1

In [3]:
from pandas import json_normalize

df_plano = json_normalize(datos_anidados)

print(df_plano)

   id_orden   monto cliente.nombre cliente.nivel
0       101  1500.5        Eduardo           VIP
1       102   800.0         Andrea       Regular
2       103  2300.1         Carlos           VIP

In [4]:
datos_tiendas = [
    {"id_tienda": 1, "ubicacion": {"ciudad": "CDMX", "coordenadas": {"lat": 19.43, "lon": -99.13}}, "ventas": 50000},
    {"id_tienda": 2, "ubicacion": {"ciudad": "Guadalajara", "coordenadas": {"lat": 20.66, "lon": -103.34}}, "ventas": 42000}
]

from pandas import json_normalize

df_datos_tienda = json_normalize(datos_tiendas)

df_datos_tienda

,id_tienda,ventas,ubicacion.ciudad,ubicacion.coordenadas.lat,ubicacion.coordenadas.lon
0,1,50000,CDMX,19.43,-99.13
1,2,42000,Guadalajara,20.66,-103.34