In [8]:
import pandas as pd
import numpy as np

datos_credito = {
    "ID_Cliente": ["C001", "C002", "C003", "C004", "C005"],
    "Ingreso_Mensual": [25000, np.nan, 45000, 18000, np.nan],
    "Monto_Solicitado": [100000, 30000, 150000, 25000, 80000],
    "Pagos_Atrasados": [0, 2, 0, 1, 3]
}

In [9]:
df_datos = pd.DataFrame(datos_credito)

df_datos

  ID_Cliente  Ingreso_Mensual  Monto_Solicitado  Pagos_Atrasados
0       C001          25000.0            100000                0
1       C002              NaN             30000                2
2       C003          45000.0            150000                0
3       C004          18000.0             25000                1
4       C005              NaN             80000                3

In [10]:
mediana_mensual = df_datos["Ingreso_Mensual"].median()

df_datos["Ingreso_Mensual"] = df_datos["Ingreso_Mensual"].fillna(mediana_mensual)

df_datos

  ID_Cliente  Ingreso_Mensual  Monto_Solicitado  Pagos_Atrasados
0       C001          25000.0            100000                0
1       C002          25000.0             30000                2
2       C003          45000.0            150000                0
3       C004          18000.0             25000                1
4       C005          25000.0             80000                3

In [11]:
df_datos["Score_Riesgo"] = np.where((df_datos["Monto_Solicitado"] > 50000) & (df_datos["Pagos_Atrasados"] > 0), "Alto Riesgo", "Riesgo Aceptable")

df_datos

,ID_Cliente,Ingreso_Mensual,Monto_Solicitado,Pagos_Atrasados,Score_Riesgo
0,C001,25000.0,100000,0,Riesgo Aceptable
1,C002,25000.0,30000,2,Riesgo Aceptable
2,C003,45000.0,150000,0,Riesgo Aceptable
3,C004,18000.0,25000,1,Riesgo Aceptable
4,C005,25000.0,80000,3,Alto Riesgo

In [12]:
nivel_riesgo = df_datos.groupby("Score_Riesgo")["Monto_Solicitado"].sum().reset_index()

nivel_riesgo

       Score_Riesgo  Monto_Solicitado
0       Alto Riesgo             80000
1  Riesgo Aceptable            305000