In [7]:
import pandas as pd
import numpy as np

datos_suscripciones = {
    "ID_Pago": ["PAY-01", "PAY-02", "PAY-03", "PAY-04", "PAY-05", "PAY-06"],
    "Fecha_Texto": ["2026-01-15", "2026-01-22", "2026-02-05", "2026-02-19", "2026-03-02", "2026-03-15"],
    "Monto": [1500.0, 2300.0, 800.0, 3100.0, 1200.0, 4500.0],
    "Plan": ["Básico", "Pro", "Básico", "Premium", "Básico", "Premium"]
}

df_pagos = pd.DataFrame(datos_suscripciones)

df_pagos

  ID_Pago Fecha_Texto   Monto     Plan
0  PAY-01  2026-01-15  1500.0   Básico
1  PAY-02  2026-01-22  2300.0      Pro
2  PAY-03  2026-02-05   800.0   Básico
3  PAY-04  2026-02-19  3100.0  Premium
4  PAY-05  2026-03-02  1200.0   Básico
5  PAY-06  2026-03-15  4500.0  Premium

In [8]:
df_pagos['Fecha_Texto'] = pd.to_datetime(df_pagos['Fecha_Texto'])

df_pagos

  ID_Pago Fecha_Texto   Monto     Plan
0  PAY-01  2026-01-15  1500.0   Básico
1  PAY-02  2026-01-22  2300.0      Pro
2  PAY-03  2026-02-05   800.0   Básico
3  PAY-04  2026-02-19  3100.0  Premium
4  PAY-05  2026-03-02  1200.0   Básico
5  PAY-06  2026-03-15  4500.0  Premium

In [9]:
df_pagos['Mes'] = df_pagos['Fecha_Texto'].dt.month

df_pagos

  ID_Pago Fecha_Texto   Monto     Plan  Mes
0  PAY-01  2026-01-15  1500.0   Básico    1
1  PAY-02  2026-01-22  2300.0      Pro    1
2  PAY-03  2026-02-05   800.0   Básico    2
3  PAY-04  2026-02-19  3100.0  Premium    2
4  PAY-05  2026-03-02  1200.0   Básico    3
5  PAY-06  2026-03-15  4500.0  Premium    3

In [15]:
df_pagos = df_pagos.sort_values('Fecha_Texto')


df_pagos

  ID_Pago Fecha_Texto   Monto     Plan  Mes
0  PAY-01  2026-01-15  1500.0   Básico    1
1  PAY-02  2026-01-22  2300.0      Pro    1
2  PAY-03  2026-02-05   800.0   Básico    2
3  PAY-04  2026-02-19  3100.0  Premium    2
4  PAY-05  2026-03-02  1200.0   Básico    3
5  PAY-06  2026-03-15  4500.0  Premium    3

In [17]:
df_pagos['Ingreso_Acumulado'] = df_pagos['Monto'].cumsum()

df_pagos

  ID_Pago Fecha_Texto   Monto     Plan  Mes  Ingreso_Acumulado
0  PAY-01  2026-01-15  1500.0   Básico    1             1500.0
1  PAY-02  2026-01-22  2300.0      Pro    1             3800.0
2  PAY-03  2026-02-05   800.0   Básico    2             4600.0
3  PAY-04  2026-02-19  3100.0  Premium    2             7700.0
4  PAY-05  2026-03-02  1200.0   Básico    3             8900.0
5  PAY-06  2026-03-15  4500.0  Premium    3            13400.0

In [18]:
venta_por_mes = df_pagos.groupby('Mes')['Monto'].sum().reset_index()

venta_por_mes

   Mes   Monto
0    1  3800.0
1    2  3900.0
2    3  5700.0