In [15]:
import pandas as pd
import numpy as np

lecturas_iot = {
    "ID_Paciente": ["P1", "P1", np.nan, "P2", "P2", "P2"],
    "Timestamp": ["10:00", "10:05", "10:10", "10:00", "10:05", "10:10"],
    "BPM": [75, 305, 80, 62, 45, np.nan]
}

In [16]:
df_lecturas = pd.DataFrame(lecturas_iot)

df_lecturas

  ID_Paciente Timestamp    BPM
0          P1     10:00   75.0
1          P1     10:05  305.0
2         NaN     10:10   80.0
3          P2     10:00   62.0
4          P2     10:05   45.0
5          P2     10:10    NaN

In [17]:
df_lecturas = df_lecturas.dropna(subset=["ID_Paciente"])

df_lecturas

  ID_Paciente Timestamp    BPM
0          P1     10:00   75.0
1          P1     10:05  305.0
3          P2     10:00   62.0
4          P2     10:05   45.0
5          P2     10:10    NaN

In [20]:
# 1. Tu código excelente para meter los NaN a los outliers
df_lecturas["BPM"] = np.where((df_lecturas["BPM"] > 220) | (df_lecturas["BPM"] < 40), np.nan, df_lecturas["BPM"])

# 2. Calculamos los promedios sin aplastar la tabla usando transform
promedios_pacientes = df_lecturas.groupby("ID_Paciente")["BPM"].transform("mean")

# 3. Rellenamos los NaN de la columna BPM usando esos promedios calculados
df_lecturas["BPM"] = df_lecturas["BPM"].fillna(promedios_pacientes)

C:\Users\eduar\AppData\Local\Temp\ipykernel_19240\891912381.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_lecturas["BPM"] = np.where((df_lecturas["BPM"] > 220) | (df_lecturas["BPM"] < 40), np.nan, df_lecturas["BPM"])
C:\Users\eduar\AppData\Local\Temp\ipykernel_19240\891912381.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_lecturas["BPM"] = df_lecturas["BPM"].fillna(promedios_pacientes)

In [24]:
df_final = df_lecturas.iloc[-3:]
df_final

  ID_Paciente Timestamp   BPM
3          P2     10:00  62.0
4          P2     10:05  45.0
5          P2     10:10  53.5